### ISSUE TITLE
Confused: Where is oktavia-mkindex????

### ISSUE THREAD

**Issue by kyoh86** [shibukawa/oktavia#27]
I read your [Tutorial](http://oktavia.info/pages/doc/tutorial.html) and README, but I could not find "oktavia-mkindex".
When I read a gruntfile.js, find a command "grunt build".
Delete old informations and modify a README plz!!!!!!!

**Comment by kazuho** [comment]
FWIW IIRC the tutorial refers to version 0.5 (the latest release) and does not reflect the changes in master.

@shibukawa Do you recommend the users to use 0.5 for the time being?
